# docker-compose.yml
version: '3.3'

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data